import pygame
from ..constants import WELL_HEIGHT, WELL_WIDTH

LEFT_WIDTH = 2
RIGHT_WIDTH = 7
BOTTOM_HEIGHT = 2
FULL_WIDTH = WELL_WIDTH + LEFT_WIDTH + RIGHT_WIDTH
FULL_HEIGHT = WELL_HEIGHT + BOTTOM_HEIGHT
BRICK_BORDER = 7

TYPE_FACE = "freesansbold.ttf"

EVENT_TICK = pygame.USEREVENT + 0

LEVEL_TICKS = [None, 800, 700, 600, 500, 400, 300, 175, 125, 75]
